### ISSUE TITLE
You can't easily change the size of a button via a media query

### ISSUE THREAD

**Issue by 11k** [destinygg/libstiny#23]
I'd like the ability to change the size of buttons at certain screen widths. I think the best way to implement support for this is to extract the styles for large and small buttons into mixins. That way, you can conditionally apply the mixins via media queries. You can also use the mixins in the `.button--size` rulesets to avoid duplicate code.

```scss
// button.scss

@mixin button--large {
  @include icon-size($icon-md);

  gap: $button-large-gap;
  padding: 0 $button-large-padding;
  height: $button-large-height;
  font: $body-300-semi-bold;
}

.button {
  // ...

  &--large {
    @include button--large;
  }
}
```

```html
<!-- index.html -->

<button class="button button--primary">Button</button>
```

```scss
// main.scss

@media (width > 64rem) {
  .button {
    @include button--large;
  }
}
```
