### ISSUE TITLE
Chrome autofill changes input style

### ISSUE THREAD

**Issue by Mitchdev** [destinygg/libstiny#44]
![image](https://github.com/user-attachments/assets/84a86014-e5b7-4e0e-8020-d5f4a7d04e45)

Possible fix from [here](https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete)

```scss
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
input:-webkit-autofill:active {
    -webkit-box-shadow: 0 0 0 30px #18191b inset !important;  // #18191b bg-color
    -webkit-text-fill-color: #edeef0; // #edeef0 text-color
    caret-color: white;
}
```
